spring.application.name=demo

# 关闭Banner
spring.main.banner-mode=off

# -------- 核心日志控制 --------

logging.level.root=ERROR

# 关闭Spring Boot
logging.level.org.springframework.boot=OFF
logging.level.org.springframework.boot.context=OFF

# 关闭Spring
logging.level.org.springframework=OFF

# 关闭Hibernate
logging.level.org.hibernate=OFF

# 关闭Tomcat
logging.level.org.apache=OFF

# -------- 只保留自己代码 --------

logging.level.com.example.demo=DEBUG

# -------- 输出到文件 --------

logging.file.name=logs/app.log